leetcode_data_collector:
  description: >
    Collect and analyze data for a specific LeetCode profile at {leetcode_link}.
    Evaluate whether the user has solved enough problems across various types and difficulties.
    Provide a score out of 10 based on consistency, problem diversity, and difficulty levels.
    If the user excels in contests / has given many contests , a full score can be awarded.

  expected_output: >
    Provide only a score out of 10 with detailed reasoning. 
    The output should be formatted as JSON for structured integration.

  agent: candidate_manager


scholar_data_collector:
  description: >
    Analyze the candidate's Google Scholar profile at {scholar_link}. ( The part ahead of user= in the link is the authorId )
    Assess them according to the number of publications, citations, and research impact.
  expected_output: >
    A score out of 10, with reasons in JSON format.
  agent: candidate_manager


linkedin_data_collector:
  description: >
    Analyze the candidate's LinkedIn profile at {linkedin_link}.( Last part of the link is the linkedin username )
    Assess professional experience, skills, endorsements, and alignment with the job role.
  expected_output: >
    A score out of 10 for professional experience and networking, with reasons in JSON format.
  agent: candidate_manager


github_data_collector:
  description: >
    Analyze the candidate's GitHub profile at {github_link}.
    Assess the quality and variety of projects, contribution frequency, and technical depth.
  expected_output: >
    A score out of 10 for technical project work and collaboration, with reasons in JSON format.
  agent: candidate_manager